In [18]:
import urllib.request
import json                 # Used to load data into JSON format
from pprint import pprint   # pretty-print

In [ ]:
import pandas as pd

frames = []
for start in [1, 10001, 20001, 30001]:
    count = 10000 if start < 30001 else 6454
    url = f"https://aoe2.net/api/leaderboard?game=aoe2de&leaderboard_id=3&start={start}&count={count}"
    response = urllib.request.urlopen(url)
    text = response.read()
    json_data = json.loads(text)
    
    df = pd.DataFrame(data=json_data['leaderboard'])
    df = df.set_index('rank')
    frames.append(df)

leaderboard = pd.concat(frames)

In [50]:
leaderboard.head()

,profile_id,rating,steam_id,icon,name,clan,country,previous_rating,highest_rating,streak,lowest_streak,highest_streak,games,wins,losses,drops,last_match,last_match_time
rank,,,,,,,,,,,,,,,,,,
1,251265,2324,76561197996386232,None,[aM] MbL40C,None,NO,2322.0,2372.0,3,-9.0,17.0,1519,1054,465,80,1594679211,1594679211
2,208393,2316,76561198027378107,None,Nicov,None,AR,2312.0,2316.0,13,-4.0,19.0,601,449,152,6,1594642838,1594642838
3,197388,2308,76561198088251629,None,Secret TaToH,TaToH,ES,2300.0,2343.0,1,-5.0,21.0,416,298,118,3,1594491890,1594491890
4,199325,2303,76561198449406083,None,[aM] Hera,None,CA,2315.0,2373.0,-2,-6.0,21.0,1399,945,454,10,1594675885,1594675885
5,196240,2298,76561197984749679,None,TheViper,None,DE,2288.0,2341.0,2,-5.0,22.0,470,328,142,1,1594417850,1594417850

In [51]:
leaderboard.tail()

,profile_id,rating,steam_id,icon,name,clan,country,previous_rating,highest_rating,streak,lowest_streak,highest_streak,games,wins,losses,drops,last_match,last_match_time
rank,,,,,,,,,,,,,,,,,,
36450,2113892,242,76561199040790084,None,Liewe Heksie,None,ZA,245.0,719.0,-1,-10.0,3.0,104,24,80,2,1594213492,1594213492
36451,1950140,242,76561198151504398,None,Suit up bro,None,US,253.0,743.0,-19,-19.0,4.0,77,16,61,5,1593809948,1593809948
36452,2573338,218,None,None,goprogambler,None,None,225.0,672.0,-9,-40.0,5.0,249,40,209,37,1594618993,1594618993
36453,2750718,191,76561198380626512,None,wayneniky,None,GH,196.0,758.0,-1,-19.0,3.0,71,11,60,8,1594576128,1594576128
36454,378095,175,76561198435270845,None,lauran1,ITA,IT,186.0,688.0,-12,-17.0,1.0,59,5,54,1,1592601275,1592601275

In [53]:
leaderboard = leaderboard.drop(['clan','country','icon','previous_rating','steam_id'], axis=1)
leaderboard.head()

,profile_id,rating,name,highest_rating,streak,lowest_streak,highest_streak,games,wins,losses,drops,last_match,last_match_time
rank,,,,,,,,,,,,,
1,251265,2324,[aM] MbL40C,2372.0,3,-9.0,17.0,1519,1054,465,80,1594679211,1594679211
2,208393,2316,Nicov,2316.0,13,-4.0,19.0,601,449,152,6,1594642838,1594642838
3,197388,2308,Secret TaToH,2343.0,1,-5.0,21.0,416,298,118,3,1594491890,1594491890
4,199325,2303,[aM] Hera,2373.0,-2,-6.0,21.0,1399,945,454,10,1594675885,1594675885
5,196240,2298,TheViper,2341.0,2,-5.0,22.0,470,328,142,1,1594417850,1594417850

In [54]:
leaderboard.shape

(36454, 13)

In [ ]:
#leaderboard.isnull().sum().sum()

In [ ]:
#leaderboard.isnull().sum()

In [ ]:
#leaderboard.dropna().isnull().sum()

In [ ]:
#leaderboard = leaderboard.dropna()
leaderboard.head()

In [ ]:
#leaderboard.isnull().sum().sum()

In [55]:
leaderboard.to_csv("leaderboard.csv")